---
- hosts: "{{ deploy_host | default('dev') }}"
  gather_facts: true
  remote_user: "{{remote_user}}"
  become: false
  vars:
    base_dir: "~/app/"
    project_id: "blogposts-api"
    war_name: "blogposts.war"
    deploy_context_root: "blogposts"
    spring_profiles_active: "local"
    package_base_dir: "{{inventory_dir | dirname}}"
    tomcat_base_dir: "/opt/tomcat"
  tasks:
    - stat: path="{{tomcat_base_dir}}/bin/setenv.sh" follow=yes
      register: setenv_status
      become: true

    - name: create blank 'setenv'
      file:
        path: "{{tomcat_base_dir}}/bin/setenv.sh"
        follow: yes
        state: touch
        owner: tomcat
        group: tomcat
        mode: 0755
      when: setenv_status.stat.exists is defined and not setenv_status.stat.exists
      become: true

    - name: "Ensures {{tomcat_base_dir}}/bin/setenv.sh exists"
      file:
        path: "{{tomcat_base_dir}}/bin/setenv.sh"
        follow: yes
        state: file
        mode: 0755
        owner: tomcat
        group: tomcat
      become: true
      
    - name: Set the SPRING_PROFILES_ACTIVE in setenv.sh to keep it permanent
      lineinfile: "dest={{tomcat_base_dir}}/bin/setenv.sh line='export SPRING_PROFILES_ACTIVE=${deploy_host}' insertafter='EOF' state=present mode=0755 follow=yes"
      become: true
      
#    - name: ensure SPRING_PROFILES_ACTIVE environment variable
#      shell: "source {{tomcat_base_dir}}/bin/setenv.sh && echo $SPRING_PROFILES_ACTIVE"
#      become: true
#      become_user: tomcat
#      args:
#        executable: "/bin/bash"
#      register: spring_profiles_active_value
#    
#    - debug: var=spring_profiles_active_value
    
    - name: "configure the {{war_name}} API"
      debug:
        msg: "configure the {{war_name}} API"
    - name: "Ensures {{tomcat_base_dir}}/webapps/{{deploy_context_root}} dir exists"
      file:
        path: "{{tomcat_base_dir}}/webapps/{{deploy_context_root}}"
        follow: yes
        state: directory
      become: true

    - name: Ensure gtar/unzip is installed on target machine
      package: name=unzip state=present
      become: true

    - name: Unzip WAR file
      unarchive:
        src: "{{ playbook_dir }}/target/{{ war_name }}"
        dest: "{{tomcat_base_dir}}/webapps/{{deploy_context_root}}/"
        follow: yes
        mode: 0755
        owner: tomcat
        group: tomcat
      become: true

    - name: Permissions for the artifacts
      file:
        path: "{{tomcat_base_dir}}/webapps/{{deploy_context_root}}/"
        follow: yes
        mode: 0775
        owner: tomcat
        group: tomcat
        recurse: yes
      become: true
      
    - name: restart tomcat
      service: name=tomcat state=restarted
      become: true